name: Tests

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8.3
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: docker-compose up -d
      - run: |
          for count in {1..30}; do
            echo "Pinging mysql database attempt "${count}
            if  $(nc -z localhost 5432) ; then
              echo "Can connect into database"
              break
            fi
            sleep 1
          done
      - run: python manage.py test --settings=otomoto.settings.dev